# Step 1: Front
FROM node:20-slim AS front

WORKDIR /app
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY _front/ _front/

EXPOSE 5173

# Step 2: App
FROM python:3.11.12-slim AS app

WORKDIR /app

ENV PYDEVD_DISABLE_FILE_VALIDATION=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV DJANGO_RUNSERVER_HIDE_WARNING="true"
ENV DOCKERED=1

RUN apt update && \
    apt install -y \
    build-essential \
    libcairo2-dev \
    pkg-config \
    python3-dev && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

COPY requirements.txt .
COPY requirements-dev.txt .

RUN pip install --no-cache-dir -r requirements-dev.txt

COPY . .

EXPOSE 5678
EXPOSE 8000
