# Generated by Django 5.2 on 2025-04-17 14:36

import django.db.models.deletion
import filer.fields.image
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated_on')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('title', models.CharField(blank=True, max_length=128, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('date_in', models.DateTimeField(blank=True, null=True, verbose_name='date in')),
                ('date_out', models.DateTimeField(blank=True, null=True, verbose_name='date out')),
                ('gtm_id', models.CharField(blank=True, null=True, verbose_name='GTM ID')),
                ('image', filer.fields.image.FilerImageField(blank=True, help_text='Default: 1200x630px. Will be resized', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seo_image', to=settings.FILER_IMAGE_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
