# Generated by Django 5.2 on 2025-04-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_config_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='gtm_id',
            field=models.CharField(blank=True, help_text='Something like GTM-XXXXXXX', null=True, verbose_name='GTM ID'),
        ),
    ]
